/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'FetchXpl': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string; totalBuyOrders: number; totalSellOrders: number; totalEntries: number }> | ApiResponse<500, { success: boolean; error: string }>, never>
  }
}